const projects = [
  {
    slug: "dashboard-personal",
    title: "Dashboard Personal",
    desc: "Dashboard personal con Kanban, Pomodoro y clima.",
    icon: "fa-chart-simple",
    gradient: "from-[#22d3ee]/20 to-blue-500/20",
    iconColor: "text-[#22d3ee]",
    tags: ["JavaScript", "CSS3", "HTML5", "PHP"],
    client: "Proyecto personal",
    year: 2026,
    fullDesc:
      "Dashboard personal todo-en-uno que integra un tablero Kanban para gestión de tareas, un temporizador Pomodoro para productividad y un widget del clima. Diseñado para mantener el enfoque y organizar el día a día desde una sola interfaz limpia y minimalista.",
    features: [
      "Tablero Kanban con arrastrar y soltar",
      "Temporizador Pomodoro configurable",
      "Widget de clima con geolocalización",
      "Persistencia de datos en localStorage",
      "Interfaz responsive y modo oscuro",
    ],
    link: "https://github.com/xdlimadev/dashboard-personal",
  },
  {
    slug: "dezapas",
    title: "Dezapas",
    desc: "Plataforma web para gestión de anuncios clasificados.",
    icon: "fa-tag",
    gradient: "from-purple-500/20 to-pink-500/20",
    iconColor: "text-purple-400",
    tags: ["PHP", "MySQL", "CSS3"],
    client: "Proyecto académico — FP MEDAC",
    year: 2026,
    fullDesc:
      'Aplicación web completa de anuncios clasificados desarrollada como proyecto para la asignatura "Desarrollo web en entorno de servidor". Los usuarios pueden registrarse, publicar anuncios con imágenes, buscar por categorías y contactar con vendedores. Incluye panel de administración.',
    features: [
      "Registro y autenticación de usuarios",
      "Publicación de anuncios con imágenes",
      "Búsqueda y filtrado por categorías",
      "Panel de administración",
      "Sistema de mensajería interna",
    ],
    link: "https://github.com/xdlimadev/dezapas",
  },
  {
    slug: "dental-clinic-app",
    title: "Dental Clinic App",
    desc: "Aplicación web para la gestión de una clínica dental.",
    icon: "fa-tooth",
    gradient: "from-emerald-500/20 to-teal-500/20",
    iconColor: "text-emerald-400",
    tags: ["HTML5", "CSS3", "JavaScript"],
    client: "Proyecto académico — Entorno Cliente",
    year: 2025,
    fullDesc:
      'Aplicación frontend para la gestión de citas y pacientes de una clínica dental. Desarrollada como trabajo de enfoque para la asignatura "Desarrollo web en entorno cliente". Interfaz interactiva con validación de formularios y gestión dinámica del DOM.',
    features: [
      "Gestión de citas y pacientes",
      "Validación de formularios en cliente",
      "Interfaz dinámica con JavaScript",
      "Diseño responsive",
      "Exportación de datos",
    ],
    link: "https://github.com/xdlimadev/dental-clinic-app",
  },
  {
    slug: "wordlegame",
    title: "WordleGame",
    desc: "Clon del popular juego Wordle desarrollado en Java.",
    icon: "fa-keyboard",
    gradient: "from-amber-500/20 to-orange-500/20",
    iconColor: "text-amber-400",
    tags: ["Java", "Swing"],
    client: "Proyecto personal",
    year: 2025,
    fullDesc:
      "Implementación del clásico juego Wordle en Java con interfaz gráfica Swing. El jugador tiene 6 intentos para adivinar una palabra de 5 letras, con retroalimentación visual por colores. Incluye un diccionario integrado y estadísticas de partidas.",
    features: [
      "Interfaz gráfica con Java Swing",
      "Sistema de pistas por colores",
      "Diccionario de palabras integrado",
      "Estadísticas de partidas",
      "Animaciones y efectos visuales",
    ],
    link: "https://github.com/xdlimadev/wordlegame",
  },
  {
    slug: "lenguajedemarcas",
    title: "Lenguaje de Marcas",
    desc: "Trabajo de enfoque con XML, XSLT y diseño web.",
    icon: "fa-file-code",
    gradient: "from-cyan-500/20 to-blue-500/20",
    iconColor: "text-cyan-400",
    tags: ["XML", "XSLT", "HTML5", "CSS3"],
    client: "Proyecto académico — Lenguaje de Marcas",
    year: 2025,
    fullDesc:
      'Proyecto integral de la asignatura "Lenguaje de Marcas" que abarca desde la creación de documentos XML bien formados hasta la transformación con XSLT y la presentación visual con HTML y CSS. Demuestra el dominio de lenguajes de marcado y su aplicación práctica.',
    features: [
      "Documentos XML con esquemas DTD y XSD",
      "Transformaciones XSLT avanzadas",
      "Maquetación con HTML5 semántico",
      "Estilos CSS3 con diseño responsive",
      "Documentación técnica completa",
    ],
    link: "https://github.com/xdlimadev/lenguajedemarcas",
  },
  {
    slug: "entornodedesarrollo",
    title: "Entorno de Desarrollo",
    desc: "Proyecto Java con pruebas unitarias y control de versiones.",
    icon: "fa-flask",
    gradient: "from-rose-500/20 to-pink-500/20",
    iconColor: "text-rose-400",
    tags: ["Java", "JUnit", "Git"],
    client: "Proyecto académico — Entornos de Desarrollo",
    year: 2024,
    fullDesc:
      'Trabajo de enfoque para la asignatura "Entornos de Desarrollo" que cubre el ciclo completo de desarrollo de software: análisis, diseño, implementación en Java, pruebas unitarias con JUnit, control de versiones con Git y documentación técnica.',
    features: [
      "Programación orientada a objetos en Java",
      "Pruebas unitarias con JUnit",
      "Control de versiones con Git",
      "Diagramas UML",
      "Documentación con Javadoc",
    ],
    link: "https://github.com/xdlimadev/entornodedesarrollo",
  },
  {
    slug: "visitasvirtuales",
    title: "Visitas Virtuales",
    desc: "Plataforma de visitas virtuales inmersivas con Unity y web.",
    icon: "fa-cube",
    gradient: "from-indigo-500/20 to-violet-500/20",
    iconColor: "text-indigo-400",
    tags: ["React", "JavaScript", "C#", "Unity", "Tailwind"],
    client: "Proyecto colaborativo",
    year: 2025,
    fullDesc:
      "Plataforma de visitas virtuales que permite a usuarios explorar instalaciones de forma inmersiva. Combina un frontend web moderno con TypeScript, una API backend y una experiencia 3D potenciada por Unity para ofrecer recorridos virtuales interactivos y realistas.",
    features: [
      "Recorridos virtuales 3D con Unity",
      "Frontend web con TypeScript",
      "API backend para gestión de datos",
      "Visualización inmersiva de instalaciones",
      "Arquitectura documentada y escalable",
    ],
    link: "https://github.com/xdlimadev/VisitasVirtuales",
  },
];

export default projects;
